[package]
name = "pruning_dfs_ymatsux_improved"
description.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[features]
benchmark = []

[lib]
bench = false

[[bench]]
name = "shanten"
path = "benches/shanten.rs"
required-features = ["benchmark"]

[lints]
workspace = true

[dependencies]
common.workspace = true
